name: mernapp  # ✅ Lowercased

services:
  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db  # ✅ Uses the fixed volume
    networks:
      - mernapp  

  # Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: 
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mernapp  
    command: npm run dev

  # Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mernapp  
    command: npm run dev

volumes:
  mongo_data: {}  # ✅ FIXED (valid mapping)

networks:
  mernapp:
    driver: bridge
